


# Shadowrocket: 2025-08-13 12:07:03
[General]
# 默认关闭 ipv6 支持，如果需要请手动开启
ipv6 = false
bypass-system = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, fe80::/10, fc00::/7, localhost, *.local, *.lan, *.internal, e.crashlytics.com, captive.apple.com, sequoia.apple.com, seed-sequoia.siri.apple.com, *.ls.apple.com
bypass-tun = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.18.0.0/15,198.51.100.0/24,203.0.113.0/24,233.252.0.0/24,224.0.0.0/4,255.255.255.255/32,::1/128,::ffff:0:0/96,::ffff:0:0:0/96,64:ff9b::/96,64:ff9b:1::/48,100::/64,2001::/32,2001:20::/28,2001:db8::/32,2002::/16,3fff::/20,5f00::/16,fc00::/7,fe80::/10,ff00::/8
dns-server = https://dns.alidns.com/dns-query, https://doh.pub/dns-query

[Rule]
# RenzheCloud服务
DOMAIN-SUFFIX,renzhecloud.com,Proxy
DOMAIN-SUFFIX,renzhe.cloud.com,Proxy
DOMAIN-SUFFIX,renzhe.cloud,Proxy

DOMAIN-SUFFIX,cloudflare-ipfs.com,Proxy
DOMAIN-SUFFIX,cloudflare.cdn.openbsd.org,Proxy
DOMAIN-SUFFIX,cloudflarewarp.com,Proxy
DOMAIN-SUFFIX,cloudflare-dns.com,Proxy

DOMAIN-SUFFIX,gravatar.com,Proxy
DOMAIN-SUFFIX,googleapis.com,Proxy
DOMAIN-SUFFIX,gstatic.com,Proxy

# test
DOMAIN-SUFFIX,clients4.google.com,Proxy
DOMAIN-SUFFIX,optimizationguide-pa.googleapis.com,Proxy
DOMAIN-SUFFIX,bs3.jymzffbquawl.com,Proxy
DOMAIN-SUFFIX,telegram.org,Proxy
DOMAIN-SUFFIX,client.relay.crisp.chat,Proxy
DOMAIN-SUFFIX,oauth.telegram.org,Proxy
DOMAIN-SUFFIX,content-autofill.googleapis.com,Proxy
DOMAIN-SUFFIX,passwordsleakcheck-pa.googleapis.com,Proxy
DOMAIN-SUFFIX,mtalk.google.com,Proxy
DOMAIN-SUFFIX,iphone-ld.apple.com,Proxy
DOMAIN-SUFFIX,ocsp2.apple.com,Proxy

# ChatGPT / OpenAI
DOMAIN-SUFFIX,openai.com,PROXY
DOMAIN-SUFFIX,chat.openai.com,PROXY
DOMAIN-SUFFIX,api.openai.com,PROXY

# Google 服务走代理
DOMAIN-SUFFIX,google.com,PROXY
DOMAIN-SUFFIX,googleapis.com,PROXY
DOMAIN-SUFFIX,ggpht.com,PROXY
DOMAIN-SUFFIX,gstatic.com,PROXY
DOMAIN-SUFFIX,googleusercontent.com,PROXY

# github
DOMAIN-SUFFIX,raw.githubusercontent.com,PROXY
# GitHub在线编辑器
DOMAIN-SUFFIX,github.dev,PROXY

# New Bing
# DOMAIN-SUFFIX,bing.com,PROXY

# 其他国内网站直连
FINAL,DIRECT

[URL Rewrite]
^https?://(www.)?(g|google)\.cn https://www.google.com 302

# Made with Love from https://github.com/Johnshall/Shadowrocket-ADBlock-Rules-Forever
